version: '3'

services:
  rabbitmq:
    image: my-rabbit-image
    build:
      context: ./rabbitMQ
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

volumes:
  redis_data:

